# Generated by Django 5.1.3 on 2024-12-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title for hero section', max_length=200)),
                ('describtion', models.TextField(help_text='short describtion for website', max_length=500)),
            ],
        ),
    ]
