# Generated by Django 5.1.3 on 2024-12-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='describtion',
            new_name='description',
        ),
    ]
