# Generated by Django 5.1.3 on 2024-12-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='enter service image', upload_to='services/images/'),
        ),
    ]
