# Generated by Django 5.1.3 on 2024-12-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('time_to_contact', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10)),
                ('service', models.CharField(max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('waiting on client response', 'waiting on client response'), ('resolved', 'resolved')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
