# Generated by Django 5.1.3 on 2024-12-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicebooked'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceBooked',
            new_name='BookedService',
        ),
    ]
