# Generated by Django 5.1.3 on 2024-12-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_servicebooked_bookedservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedservice',
            name='preferred_contact_method',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('WhatsApp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
