# Generated by Django 5.1.3 on 2024-12-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
