# Generated by Django 5.1.3 on 2024-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_leads_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
