# Generated by Django 5.1.3 on 2024-12-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emailcampaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcampaign',
            options={},
        ),
    ]
