# Generated by Django 5.1.4 on 2024-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceShop', '0006_orderitem_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
