# Generated by Django 5.1.4 on 2024-12-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceShop', '0008_alter_orderitem_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_instock',
            field=models.BooleanField(default=True),
        ),
    ]
